In [89]:
import pandas as pd

In [90]:
df = pd.read_csv("../data/raw/sales.csv")

In [91]:
df.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Location_ID,Quantity,Sales,Discount,Cost,Profit,Return_Flag
0,ORD00001,2026-02-06 11:06:52,CUST0842,PROD099,LOC006,5,40239.43,0.15,24963.80,9239.72,No
1,ORD00002,2026-05-22 01:21:57,CUST0198,PROD042,LOC009,1,47436.49,0.05,37478.15,7586.52,Yes
2,ORD00003,2026-02-19 03:40:37,CUST0008,PROD081,LOC002,2,33681.59,0.05,25353.24,6644.27,No
3,ORD00004,2025-03-22 17:20:10,CUST0211,PROD069,LOC014,4,32504.78,0.00,23124.28,9380.50,No
4,ORD00005,2025-01-19 10:47:13,CUST0471,PROD092,LOC006,1,4832.28,0.00,2475.56,2356.72,No

In [92]:
df.shape

(12020, 11)

In [93]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Location_ID',
       'Quantity', 'Sales', 'Discount', 'Cost', 'Profit', 'Return_Flag'],
      dtype='object')

In [94]:
df = df.drop_duplicates()

In [95]:
df[df["Sales"].isnull()]

,Order_ID,Order_Date,Customer_ID,Product_ID,Location_ID,Quantity,Sales,Discount,Cost,Profit,Return_Flag
839,ORD00840,2025-04-06 07:00:05,CUST0110,PROD019,LOC005,3,NaN,0.00,21365.20,23417.74,No
1621,ORD01622,2026-03-31 20:45:24,CUST0338,PROD058,LOC003,5,NaN,0.20,14122.13,7378.65,No
2447,ORD02448,2025-12-11 13:19:36,CUST0444,PROD031,LOC009,1,NaN,0.20,12561.78,9219.50,No
3132,ORD03133,2025-04-13 23:55:11,CUST0667,PROD022,LOC011,2,NaN,0.10,17810.71,15382.44,Yes
3437,ORD03438,2026-01-14 15:10:05,CUST0726,PROD012,LOC006,3,NaN,0.15,7761.65,6306.85,Yes
4132,ORD04133,2026-06-25 19:15:33,CUST0942,PROD030,LOC001,3,NaN,0.10,9894.04,2702.22,No
4459,ORD04460,2025-09-13 02:13:11,CUST0203,PROD078,LOC001,5,NaN,0.05,16104.71,6370.36,No
4902,ORD04903,2026-01-06 19:03:55,CUST0077,PROD081,LOC011,2,NaN,0.00,34075.59,9363.25,No
5559,ORD05560,2025-01-14 11:56:48,CUST0337,PROD002,LOC014,4,NaN,0.20,26927.64,8365.93,Yes
6170,ORD06171,2025-01-27 21:47:59,CUST0286,PROD015,LOC012,2,NaN,0.15,14909.68,3107.75,No
6778,ORD06779,2025-03-21 07:23:56,CUST0170,PROD020,LOC005,4,NaN,0.10,15030.59,2785.13,Yes
7307,ORD07308,2026-04-21 07:01:19,CUST0173,PROD060,LOC012,5,NaN,0.25,4416.07,406.47,No
7852,ORD07853,2025-11-13 16:16:56,CUST0720,PROD021,LOC003,2,NaN,0.00,30719.00,17271.15,No
8108,ORD08109,2026-01-22 18:14:13,CUST0367,PROD005,LOC010,3,NaN,0.05,2731.78,513.70,No
11572,ORD11573,2025-06-11 17:25:13,CUST0962,PROD072,LOC011,3,NaN,0.25,37109.15,-2285.97,No

In [96]:
df.loc[df["Sales"].isnull(), "Sales"] = (
    df.loc[df["Sales"].isnull(), "Profit"] +
    df.loc[df["Sales"].isnull(), "Cost"]
) / (1 - df.loc[df["Sales"].isnull(), "Discount"])

In [97]:
df["Sales"].isnull().sum()

np.int64(0)

In [98]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [99]:
df["Order_Date"].dtype

dtype('<M8[ns]')

In [100]:
#####tjhis after

In [101]:
df.describe()

,Order_Date,Quantity,Sales,Discount,Cost,Profit
count,12000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000
mean,2025-10-01 05:41:47.350000128,3.029750,25423.282616,0.125054,15898.756492,6367.952056
min,2025-01-01 00:57:37,1.000000,502.640000,0.000000,281.100000,-2285.970000
25%,2025-05-17 02:11:26.500000,2.000000,13101.472500,0.050000,7969.545000,2049.030000
50%,2025-10-02 08:29:37.500000,3.000000,25574.275000,0.150000,15578.730000,5167.715000
75%,2026-02-15 01:06:55.500000,4.000000,37744.660000,0.200000,22885.092500,9579.565000
max,2026-06-29 23:57:18,5.000000,49991.320000,0.250000,39622.960000,26593.470000
std,NaN,1.420927,14237.624234,0.085483,9365.446613,5298.457053

In [102]:
df["Calculated_Profit"] = df["Sales"] - df["Cost"]

In [103]:
(df["Profit"] - df["Calculated_Profit"]).describe()

count    1.200000e+04
mean    -3.156574e+03
std      3.023654e+03
min     -1.249773e+04
25%     -4.910325e+03
50%     -2.248085e+03
75%     -6.093475e+02
max      5.456968e-12
dtype: float64

In [104]:
df["Calculated_Profit"] = df["Sales"] - df["Cost"] - (df["Sales"] * df["Discount"])

In [105]:
(df["Profit"] - df["Calculated_Profit"]).describe()

count    12000.000000
mean        -0.000022
std          0.002678
min         -0.005000
25%         -0.002000
50%          0.000000
75%          0.002000
max          0.005000
dtype: float64

In [106]:
df.drop("Calculated_Profit", axis=1, inplace=True)

In [107]:
df.shape

(12000, 11)

In [108]:
df["Order_ID"].duplicated().sum()

np.int64(0)

In [109]:
print("Customers:", df["Customer_ID"].nunique())
print("Products:", df["Product_ID"].nunique())
print("Locations:", df["Location_ID"].nunique())

Customers: 1000
Products: 100
Locations: 14

In [110]:
df["Return_Flag"].value_counts()

Return_Flag
No     9618
Yes    2382
Name: count, dtype: int64

In [111]:
print(df["Return_Flag"].unique())
print(df["Location_ID"].unique())

['No' 'Yes']
['LOC006' 'LOC009' 'LOC002' 'LOC014' 'LOC007' 'LOC013' 'LOC012' 'LOC011'
 'LOC001' 'LOC010' 'LOC008' 'LOC003' 'LOC005' 'LOC004']

In [112]:
df["Year"] = df["Order_Date"].dt.year

In [113]:
df[["Order_Date", "Year"]].head()

           Order_Date  Year
0 2026-02-06 11:06:52  2026
1 2026-05-22 01:21:57  2026
2 2026-02-19 03:40:37  2026
3 2025-03-22 17:20:10  2025
4 2025-01-19 10:47:13  2025

In [114]:
df["Month"] = df["Order_Date"].dt.month

In [115]:
df[["Order_Date", "Year", "Month"]].head()

           Order_Date  Year  Month
0 2026-02-06 11:06:52  2026      2
1 2026-05-22 01:21:57  2026      5
2 2026-02-19 03:40:37  2026      2
3 2025-03-22 17:20:10  2025      3
4 2025-01-19 10:47:13  2025      1

In [116]:
df["Month_Name"] = df["Order_Date"].dt.month_name()

In [117]:
df[["Order_Date", "Year", "Month", "Month_Name"]].head()

           Order_Date  Year  Month Month_Name
0 2026-02-06 11:06:52  2026      2   February
1 2026-05-22 01:21:57  2026      5        May
2 2026-02-19 03:40:37  2026      2   February
3 2025-03-22 17:20:10  2025      3      March
4 2025-01-19 10:47:13  2025      1    January

In [118]:
df["Quarter"] = df["Order_Date"].dt.quarter

In [119]:
df[["Order_Date", "Year", "Month", "Month_Name", "Quarter"]].head()

           Order_Date  Year  Month Month_Name  Quarter
0 2026-02-06 11:06:52  2026      2   February        1
1 2026-05-22 01:21:57  2026      5        May        2
2 2026-02-19 03:40:37  2026      2   February        1
3 2025-03-22 17:20:10  2025      3      March        1
4 2025-01-19 10:47:13  2025      1    January        1

In [120]:
df["Quarter_Name"] = "Q" + df["Quarter"].astype(str)

In [121]:
df[["Order_Date", "Year", "Month_Name", "Quarter", "Quarter_Name"]].head()

           Order_Date  Year Month_Name  Quarter Quarter_Name
0 2026-02-06 11:06:52  2026   February        1           Q1
1 2026-05-22 01:21:57  2026        May        2           Q2
2 2026-02-19 03:40:37  2026   February        1           Q1
3 2025-03-22 17:20:10  2025      March        1           Q1
4 2025-01-19 10:47:13  2025    January        1           Q1

In [122]:
df["Discount_Amount"] = df["Sales"] * df["Discount"]

In [123]:
df[["Sales", "Discount", "Discount_Amount"]].head()

      Sales  Discount  Discount_Amount
0  40239.43      0.15        6035.9145
1  47436.49      0.05        2371.8245
2  33681.59      0.05        1684.0795
3  32504.78      0.00           0.0000
4   4832.28      0.00           0.0000

In [124]:
df["Profit_Margin"] = (df["Profit"] / df["Sales"]) * 100

df[["Sales", "Profit", "Profit_Margin"]].head()

      Sales   Profit  Profit_Margin
0  40239.43  9239.72      22.961856
1  47436.49  7586.52      15.993005
2  33681.59  6644.27      19.726711
3  32504.78  9380.50      28.858832
4   4832.28  2356.72      48.770353

In [125]:
df["Return_Flag_Num"] = df["Return_Flag"].map({
    "Yes": 1,
    "No": 0
})

df[["Return_Flag", "Return_Flag_Num"]].head()

  Return_Flag  Return_Flag_Num
0          No                0
1         Yes                1
2          No                0
3          No                0
4          No                0

In [126]:
df.to_csv("sales_data_cleaned.csv", index=False)

In [127]:
df["Year_Month"] = df["Order_Date"].dt.to_period("M").astype(str)

In [128]:
df[["Order_Date", "Year_Month"]].head()

           Order_Date Year_Month
0 2026-02-06 11:06:52    2026-02
1 2026-05-22 01:21:57    2026-05
2 2026-02-19 03:40:37    2026-02
3 2025-03-22 17:20:10    2025-03
4 2025-01-19 10:47:13    2025-01

In [129]:
df.to_csv("sales_data_cleaned.csv", index=False)

In [130]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Location_ID',
       'Quantity', 'Sales', 'Discount', 'Cost', 'Profit', 'Return_Flag',
       'Year', 'Month', 'Month_Name', 'Quarter', 'Quarter_Name',
       'Discount_Amount', 'Profit_Margin', 'Return_Flag_Num', 'Year_Month'],
      dtype='object')

In [131]:
df.to_csv("sales_data_cleaned.csv", index=False)

In [132]:
customers = pd.read_csv("../data/raw/customers.csv")
customers.head()

  Customer_ID Customer_Name   Age  Gender  Segment Location_ID
0    CUST0001   Ravi Sharma  19.0  Female      New      LOC002
1    CUST0002     Vijay Raj  65.0    Male  Premium      LOC003
2    CUST0003    Ajay Reddy  23.0  Female      New      LOC014
3    CUST0004   Arun Sharma  31.0    Male  Premium      LOC005
4    CUST0005   Sneha Kumar  53.0    Male  Premium      LOC006

In [133]:
customers["Age"].median()

np.float64(41.0)

In [134]:
customers["Age"] = customers["Age"].fillna(customers["Age"].median())

In [135]:
customers.isnull().sum()

Customer_ID      0
Customer_Name    0
Age              0
Gender           0
Segment          0
Location_ID      0
dtype: int64

In [136]:
customers.duplicated().sum()

np.int64(0)

In [137]:
customers["Segment"].value_counts()

Segment
Regular    348
Premium    331
New        321
Name: count, dtype: int64

In [138]:
customers["Location_ID"].value_counts()

Location_ID
LOC006    88
LOC012    83
LOC011    82
LOC009    80
LOC014    75
LOC005    74
LOC003    71
LOC001    69
LOC007    68
LOC002    68
LOC004    66
LOC008    62
LOC013    59
LOC010    55
Name: count, dtype: int64

In [139]:
customers.to_csv("customers_cleaned.csv", index=False)

In [140]:
customers.shape

(1000, 6)

In [141]:
pd.read_csv("customers_cleaned.csv").head()

  Customer_ID Customer_Name   Age  Gender  Segment Location_ID
0    CUST0001   Ravi Sharma  19.0  Female      New      LOC002
1    CUST0002     Vijay Raj  65.0    Male  Premium      LOC003
2    CUST0003    Ajay Reddy  23.0  Female      New      LOC014
3    CUST0004   Arun Sharma  31.0    Male  Premium      LOC005
4    CUST0005   Sneha Kumar  53.0    Male  Premium      LOC006

In [142]:
import os

os.listdir()

['customers_cleaned.csv',
 'data_cleaning.ipynb',
 'locations_cleaned.csv',
 'products_cleaned.csv',
 'sales_data_cleaned.csv']

In [143]:
locations = pd.read_csv("../data/raw/locations.csv")

In [144]:
locations.shape

(14, 4)

In [145]:
locations.columns

Index(['Location_ID', 'City', 'State', 'Region'], dtype='object')

In [146]:
locations.dtypes

Location_ID    object
City           object
State          object
Region         object
dtype: object

In [147]:
locations["Region"].value_counts()

Region
South    5
West     3
North    3
East     3
Name: count, dtype: int64

In [148]:
locations["Location_ID"].value_counts()

Location_ID
LOC001    1
LOC002    1
LOC003    1
LOC004    1
LOC005    1
LOC006    1
LOC007    1
LOC008    1
LOC009    1
LOC010    1
LOC011    1
LOC012    1
LOC013    1
LOC014    1
Name: count, dtype: int64

In [149]:
locations.to_csv("../data/cleaned/locations_cleaned.csv", index=False)

In [150]:
pd.read_csv("../data/cleaned/locations_cleaned.csv").head()

  Location_ID        City       State Region
0      LOC001     Chennai  Tamil Nadu  South
1      LOC002  Coimbatore  Tamil Nadu  South
2      LOC003     Madurai  Tamil Nadu  South
3      LOC004   Bengaluru   Karnataka  South
4      LOC005   Hyderabad   Telangana  South

In [151]:
locations.to_csv("locations_cleaned.csv", index=False)

In [152]:
pd.read_csv("locations_cleaned.csv").shape

(14, 4)

In [153]:
products = pd.read_csv("../data/raw/products.csv")

In [154]:
products.shape

(100, 4)

In [155]:
products.columns

Index(['Product_ID', 'Product_Name', 'Category', 'Sub_Category'], dtype='object')

In [156]:
products.isnull().sum()

Product_ID      0
Product_Name    0
Category        0
Sub_Category    0
dtype: int64

In [157]:
products.duplicated().sum()

np.int64(0)

In [158]:
products["Category"].value_counts()

Category
Electronics        25
Sports             15
Clothing           15
Furniture          10
Beauty             10
Home Appliances    10
Home               10
Accessories         5
Name: count, dtype: int64

In [159]:
products["Sub_Category"].value_counts()

Sub_Category
Gadgets             25
Sports Equipment    15
Fashion             15
Furniture           10
Personal Care       10
Appliances          10
Home Decor          10
Accessories          5
Name: count, dtype: int64

In [160]:
products["Product_ID"].value_counts()

Product_ID
PROD001    1
PROD002    1
PROD003    1
PROD004    1
PROD005    1
          ..
PROD096    1
PROD097    1
PROD098    1
PROD099    1
PROD100    1
Name: count, Length: 100, dtype: int64

In [161]:
products.to_csv("products_cleaned.csv", index=False)

In [162]:
pd.read_csv("products_cleaned.csv").shape

(100, 4)

In [164]:
import pandas as pd

sales = pd.read_csv("sales_data_cleaned.csv")

In [165]:
sales.shape

(12000, 20)

In [167]:
sales.columns
sales.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Location_ID,Quantity,Sales,Discount,Cost,Profit,Return_Flag,Year,Month,Month_Name,Quarter,Quarter_Name,Discount_Amount,Profit_Margin,Return_Flag_Num,Year_Month
0,ORD00001,2026-02-06 11:06:52,CUST0842,PROD099,LOC006,5,40239.43,0.15,24963.80,9239.72,No,2026,2,February,1,Q1,6035.9145,22.961856,0,2026-02
1,ORD00002,2026-05-22 01:21:57,CUST0198,PROD042,LOC009,1,47436.49,0.05,37478.15,7586.52,Yes,2026,5,May,2,Q2,2371.8245,15.993005,1,2026-05
2,ORD00003,2026-02-19 03:40:37,CUST0008,PROD081,LOC002,2,33681.59,0.05,25353.24,6644.27,No,2026,2,February,1,Q1,1684.0795,19.726711,0,2026-02
3,ORD00004,2025-03-22 17:20:10,CUST0211,PROD069,LOC014,4,32504.78,0.00,23124.28,9380.50,No,2025,3,March,1,Q1,0.0000,28.858832,0,2025-03
4,ORD00005,2025-01-19 10:47:13,CUST0471,PROD092,LOC006,1,4832.28,0.00,2475.56,2356.72,No,2025,1,January,1,Q1,0.0000,48.770353,0,2025-01

In [168]:
customers = pd.read_csv("customers_cleaned.csv")
products = pd.read_csv("products_cleaned.csv")
locations = pd.read_csv("locations_cleaned.csv")

In [173]:

locations.shape

(14, 4)

In [174]:
sales_master = sales.merge(
    customers,
    on="Customer_ID",
    how="left"
)

In [175]:
sales_master.shape

(12000, 25)

In [176]:
sales_master.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Location_ID_x,Quantity,Sales,Discount,Cost,Profit,...,Quarter_Name,Discount_Amount,Profit_Margin,Return_Flag_Num,Year_Month,Customer_Name,Age,Gender,Segment,Location_ID_y
0,ORD00001,2026-02-06 11:06:52,CUST0842,PROD099,LOC006,5,40239.43,0.15,24963.80,9239.72,...,Q1,6035.9145,22.961856,0,2026-02,Ajay Iyer,35.0,Female,New,LOC004
1,ORD00002,2026-05-22 01:21:57,CUST0198,PROD042,LOC009,1,47436.49,0.05,37478.15,7586.52,...,Q2,2371.8245,15.993005,1,2026-05,Hari Das,54.0,Male,New,LOC011
2,ORD00003,2026-02-19 03:40:37,CUST0008,PROD081,LOC002,2,33681.59,0.05,25353.24,6644.27,...,Q1,1684.0795,19.726711,0,2026-02,Divya Patel,35.0,Male,New,LOC002
3,ORD00004,2025-03-22 17:20:10,CUST0211,PROD069,LOC014,4,32504.78,0.00,23124.28,9380.50,...,Q1,0.0000,28.858832,0,2025-03,Kavya Kumar,53.0,Female,New,LOC005
4,ORD00005,2025-01-19 10:47:13,CUST0471,PROD092,LOC006,1,4832.28,0.00,2475.56,2356.72,...,Q1,0.0000,48.770353,0,2025-01,Ravi Nair,42.0,Male,Premium,LOC013

In [177]:
sales_master[["Location_ID_x", "Location_ID_y"]].head(20)

   Location_ID_x Location_ID_y
0         LOC006        LOC004
1         LOC009        LOC011
2         LOC002        LOC002
3         LOC014        LOC005
4         LOC006        LOC013
5         LOC014        LOC003
6         LOC007        LOC012
7         LOC014        LOC006
8         LOC013        LOC010
9         LOC012        LOC003
10        LOC011        LOC005
11        LOC001        LOC012
12        LOC012        LOC008
13        LOC010        LOC009
14        LOC009        LOC002
15        LOC012        LOC010
16        LOC002        LOC012
17        LOC010        LOC006
18        LOC013        LOC002
19        LOC006        LOC011

In [178]:
(sales_master["Location_ID_x"] != sales_master["Location_ID_y"]).sum()

np.int64(11164)

In [179]:
sales_master = sales_master.drop(columns=["Location_ID_y"])

In [180]:
sales_master = sales_master.rename(columns={"Location_ID_x": "Location_ID"})

In [181]:
sales_master.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Location_ID',
       'Quantity', 'Sales', 'Discount', 'Cost', 'Profit', 'Return_Flag',
       'Year', 'Month', 'Month_Name', 'Quarter', 'Quarter_Name',
       'Discount_Amount', 'Profit_Margin', 'Return_Flag_Num', 'Year_Month',
       'Customer_Name', 'Age', 'Gender', 'Segment'],
      dtype='object')

In [182]:
sales_master.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Location_ID',
       'Quantity', 'Sales', 'Discount', 'Cost', 'Profit', 'Return_Flag',
       'Year', 'Month', 'Month_Name', 'Quarter', 'Quarter_Name',
       'Discount_Amount', 'Profit_Margin', 'Return_Flag_Num', 'Year_Month',
       'Customer_Name', 'Age', 'Gender', 'Segment'],
      dtype='object')

In [183]:
sales_master.shape

(12000, 24)

In [184]:
sales_master = sales_master.merge(
    products,
    on="Product_ID",
    how="left"
)

In [185]:
sales_master.shape

(12000, 27)

In [186]:
sales_master[["Product_ID", "Product_Name", "Category", "Sub_Category"]].head()

  Product_ID         Product_Name     Category Sub_Category
0    PROD099         Water Bottle         Home   Home Decor
1    PROD042    Bluetooth Speaker  Electronics      Gadgets
2    PROD081  Wireless Headphones  Electronics      Gadgets
3    PROD069           Power Bank  Electronics      Gadgets
4    PROD092              T-Shirt     Clothing      Fashion

In [187]:
sales_master = sales_master.merge(
    locations,
    on="Location_ID",
    how="left"
)

In [188]:
sales_master.shape

(12000, 30)

In [189]:
sales_master[["Location_ID", "City", "State", "Region"]].head()

  Location_ID        City        State Region
0      LOC006      Mumbai  Maharashtra   West
1      LOC009       Delhi        Delhi  North
2      LOC002  Coimbatore   Tamil Nadu  South
3      LOC014       Patna        Bihar   East
4      LOC006      Mumbai  Maharashtra   West

In [190]:
sales_master.isnull().sum()

Order_ID           0
Order_Date         0
Customer_ID        0
Product_ID         0
Location_ID        0
Quantity           0
Sales              0
Discount           0
Cost               0
Profit             0
Return_Flag        0
Year               0
Month              0
Month_Name         0
Quarter            0
Quarter_Name       0
Discount_Amount    0
Profit_Margin      0
Return_Flag_Num    0
Year_Month         0
Customer_Name      0
Age                0
Gender             0
Segment            0
Product_Name       0
Category           0
Sub_Category       0
City               0
State              0
Region             0
dtype: int64

In [191]:
sales_master.duplicated().sum()

np.int64(0)

In [192]:
sales_master.to_csv("sales_master_cleaned.csv", index=False)

In [193]:
pd.read_csv("sales_master_cleaned.csv").shape

(12000, 30)